#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Mon May 13 22:07:58 2024

add_design "E:/FPGA/PangoProjects/MicArray/source/MEMs_microphone_driver.v"
remove_design -verilog "E:/FPGA/PangoProjects/MicArray/source/MEMs_microphone_driver.v"
add_design "E:/FPGA/PangoProjects/MicArray/source/MEMs_microphone_driver.sv"
add_simulation "E:/FPGA/PangoProjects/MicArray/source/tb_microphone.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module MEMs_microphone_driver
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -system_verilog -top_module MEMs_microphone_driver
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -system_verilog -top_module MEMs_microphone_driver
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -system_verilog -top_module MEMs_microphone_driver
