# ----------------------------------------
# Created on: Tue May 14 01:15:54 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "F:/PDS_2022.1/sim_lib/usim"
vmap  adc "F:/PDS_2022.1/sim_lib/adc"
vmap  ddrc "F:/PDS_2022.1/sim_lib/ddrc"
vmap  ddrphy "F:/PDS_2022.1/sim_lib/ddrphy"
vmap  hsst_e2 "F:/PDS_2022.1/sim_lib/hsst_e2"
vmap  iolhr_dft "F:/PDS_2022.1/sim_lib/iolhr_dft"
vmap  ipal_e1 "F:/PDS_2022.1/sim_lib/ipal_e1"
vmap  pciegen2 "F:/PDS_2022.1/sim_lib/pciegen2"
vlog   "E:/FPGA/PangoProjects/MicArray/source/MEMs_microphone_driver.sv" -work work
vlog   "E:/FPGA/PangoProjects/MicArray/source/tb_microphone.v" -work work

# ----------------------------------------
